---
# tasks file for postgresql

- name: install progresql
  yum:
#    name: postgresql-server
    name: postgresql
    state: latest
  
- name: enable apache at boot ?????
  service:
    name: postgresql
    enabled: yes

# only run the next 2 tasks once!
- name: initilize postgres
  shell: "postgresql-setup initdb"


- name: initilize postgres some more
  shell: "chkconfig postgresql on"



#- name: start postgresql
#  service:
#    name: postgresql.service
#    name: postgresql.service
#    state: started      
