---
# tasks file for postgresql

- name: install progresql
  yum:
    name: postgresql-server
    state: latest

# only run the next 2 tasks once!
- name: initilize postgresql
  shell: "postgresql-setup initdb"

#- name: initilize postgres some more
#  shell: "chkconfig postgresql on"  

- name: enable postgresql at boot
  service:
    name: postgresql.service
    enabled: yes

- name: start postgresql
  service:
    name: postgresql.service
    state: started      
