---
# tasks file for postgresql

- name: install progresql
  yum:
    name: postgresql-server
    state: latest
  
- name: enable apache at boot
  service:
    name: postgresql
    enabled: yes

- name: start postgres
  service:
    name: postgresql.service
    state: started      
