---
# tasks file for haproxy

- name: install {{ lb_name }}
  yum:
    name: "{{ lb_name }}"
    state: latest

- name: enable {{ payload }} at boot
  service:
    name: "{{ lb_name }}"
    enabled: yes

- name: configure haproxy to load balance over app servers
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: start {{ lb_name }}
  service:
    name: "{{ lb_name }}"
    state: restarted
