---
# Katalin Kovacs

- name: configuration
  hosts: all
  gather_facts: true
  become: true
  roles:
    - role: common


- name: deploy haproxy
  hosts: frontends
  gather_facts: true
  become: true
  roles:
    - role: haproxy


- name: deploy tomcat and apache
  hosts: apps
  gather_facts: false
  become: true
  roles:
    - role: tomcat

- name: deploy postgresql
  hosts: appdbs
  gather_facts: true
  become: true
  roles:
    - role: postgresql
  

#- name: deploy apache
#  hosts: apps
#  gather_facts: true
#  become: true
#  roles:
#    - role: apache
