---
# tasks file for tomcat
- name: install {{ webserver }}
  yum:
    name: "{{ webserver }}"
    state: latest

- name: enable {{ webserver }} at boot
  service:
    name: "{{ webserver }}"
    enabled: yes

- name: create tomcat default web directory
  file:
    path: "{{ tomcat_path }}"
    state: directory

- name: copy static index.html to tomcat webroot
  template:
    src: index.html.j2
    dest: "{{ tomcat_path }}/index.html"
    mode: 0644
  notify: reload tomcat  

- name: start tomcat
  service:
    name: "{{ webserver }}"
    state: restarted

# tasks file for apache
- name: install apache
  yum:
    name: httpd
    state: latest
          
- name: enable apache at boot
  service:
    name: httpd
    enabled: yes

- name: start apache
  service:
    name: httpd
    state: started      
