---
# tasks file for common

- name: enable repos
  template:
    src: repo_list.j2
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644

 
- name: install base tools and packages
  yum:
    name: "{{ item }}" 
    state: latest
  with_items:
    - httpie
